apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mreveningeshoponcontainers 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mreveningeshoponcontainers 
    spec:
      containers:
        - name: mreveningeshoponcontainers 
          image: eshoponcontainerss.azurecr.io/mreveningeshoponcontainers
          ports:
          - containerPort: 80